### ISSUE TITLE
использование тайп хинтинга

### ISSUE THREAD

**Issue by KevinKarlBob** [FixKun/toyota_store#10]
https://github.com/FixKun/toyota_store/blob/ea6b141c80d928eaf040cabd42231754ac6dacee/src/cars/car.py#L28-L32

Если используется версия питона 3.5 и выше то возмоджно имеет смысл пользоваться тайп хинтингом.  В коде будет больше информации о используемых типах и код будет легче поддерживать
` def __init__(self, model, colour, gearbox, engine_capacity): ->__init__(self, model:int, colour:int, gearbox:int, engine_capacity:int) `

**Comment by FixKun** [comment]
Добавил.
