### ISSUE TITLE
иморт в середине класса

### ISSUE THREAD

**Issue by KevinKarlBob** [FixKun/toyota_store#11]
https://github.com/FixKun/toyota_store/blob/ea6b141c80d928eaf040cabd42231754ac6dacee/src/cars/car.py#L55-L60

Почему импорт именно здесь а не в начале классе ? Это стиль фласка ? pep 8 явно говорит "Imports are always put at the top of the file, just after any module comments and docstrings, and before module globals and constants."(https://www.python.org/dev/peps/pep-0008/#imports)

**Comment by FixKun** [comment]
Это не стиль фласка, а его проклятье. Возможно как-то и можно этого избежать, но иногда оно не стоит затраченных усилий.
