### ISSUE TITLE
Плохой нейминг 

### ISSUE THREAD

**Issue by KevinKarlBob** [FixKun/toyota_store#13]
https://github.com/FixKun/toyota_store/blob/ea6b141c80d928eaf040cabd42231754ac6dacee/src/cars/car.py#L72

start_range и end_range несут мало информации о том что это за значения(это диапазон пробега, возраста машины, размера машины?).  min_price и max_price возможно лучшее имя 

**get_cars_dict** добавление типа в имя плохая практика https://docs.quantifiedcode.com/python-anti-patterns/readability/ тем более когда оно врет написано что возвращается словарь а в действительности возвращается список словарей
для указания типа можно использовать тайп хинтинг
`def get_cars(min_price=0, max_price=None) -> List[Dict[str, str]]`

**Comment by FixKun** [comment]
fixed
