### ISSUE TITLE
requirements.txt созданный с помощью pip freeze не лучшее решение

### ISSUE THREAD

**Issue by KevinKarlBob** [FixKun/toyota_store#7]
Мы можем пропустить важные апдейты когда жестко задаем версиию https://medium.com/@tomagee/pip-freeze-requirements-txt-considered-harmful-f0bce66cf895

Так же из requirements.txt   не понятно какие билиотеки используются а какие скачались транзитивно и нет разделения на dev  и prod зависимости.  Имеет смысл расмотреть более современные инструменты для установки зависимостей как например https://python-poetry.org/

**Comment by FixKun** [comment]
discussed.
